### PR TITLE
Rule CommentRequired should be configurable

### PR DESCRIPTION
**Pull request by csatomfr**

### CODE REVIEW

**Comment by timwebster9** [comment]
Hi,

I've just taken over maintenance of this plugin.  Can you please provide a description of the pull request?  The title helps a bit, but pretend I don't know anything (for now)...:-).  Thanks.

**Comment by csatomfr** [comment]
Hi,
Sorry for my short description :P
I need to customize the CommentRequired rule because I need to use the violationSuppressXPath to suppress issues on override methods.
It could be perfect to include this parameter on next versions of sonar-pmd plugin. I'm using this version on my analysis and it works fine.
There are another 5 properties available that you can include. You can see it [here](http://pmd.sourceforge.net/pmd-5.0.4/rules/java/comments.html).
I hope that will take this into consideration.
Regards.

**Comment by timwebster9** [comment]
Hi,

I'm looking at this now.  How do you set the values of the parameters?  I can see them in the rule description, but there is no way to actually set values for them...

**Comment by timwebster9** [comment]
merged pull request 'CommentRequired should be configurable' from csatomfr

**Pull request merged**
